apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      containers:
      - name: nginx
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo thisisdev > /usr/share/nginx/html/contents.html"]
      - image: busybox:1.31.1
        name: busybox
        command: ["/bin/tail", "-f", "/dev/null"]