apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: nginx
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo thisis{{ default "dev" .Values.env }} > /usr/share/nginx/html/contents.html"]
{{- if .Values.sidecar.enabled }}
      - image: busybox:1.31.1
        name: busybox
        command: ["/bin/tail", "-f", "/dev/null"]
{{- end }}      
      serviceAccountName: nginx
      priorityClassName: nginx
        